line-length = 120
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "D101",     # undocumented-public-class
    "D103",     # undocumented-public-function
    "D104",     # undocumented-public-package
    "ARG001",   # unused-function-argument
    "PLW0603",  # global-statement
    "D100",     # undocumented-public-module
    "TC001",    # typing-only-first-party-import
    "COM812",   # missing-trailing-comma
]

exclude = [
    "scripts/add_license.py",
    "elysian_chem_bot/coloured_logging_setup.py",
]

[lint.flake8-annotations]
suppress-dummy-args = true

[lint.pydocstyle]
convention = "google"
